FPS: int = 30
FRAME_TIME: float = 1/FPS

SCREEN_WIDTH: int = 256
SCREEN_HEIGHT: int = 240

GRID_CELL_SIZE: int = 16
HALF_GRID_CELL: int = int(GRID_CELL_SIZE/2)

UI_SIZE: int = GRID_CELL_SIZE*3

ROOM_SIZE_X: int = int(SCREEN_WIDTH/GRID_CELL_SIZE)
ROOM_SIZE_Y: int = int(SCREEN_HEIGHT/GRID_CELL_SIZE - UI_SIZE/GRID_CELL_SIZE)

ROOM_SIZE_PIXELS_X: int = int(SCREEN_WIDTH)
ROOM_SIZE_PIXELS_Y: int = int(SCREEN_HEIGHT) - UI_SIZE

DEBUG_DRAW: bool = False

# Time per wave
WAVES = [90, 90, 120, 180, 120]
# Enemies per wave
WAVE_COUNT = [5, 10, 15, 20, 20]

BULLET_SPEED = 20
MOVE_ANIM_TIME = 0.6