FPS: int = 60
FRAME_TIME: float = 1/FPS

SCREEN_WIDTH: int = 256
SCREEN_HEIGHT: int = 240

GRID_CELL_SIZE: int = 16
HALF_GRID_CELL: int = int(GRID_CELL_SIZE/2)

UI_SIZE: int = GRID_CELL_SIZE*2

ROOM_SIZE_X: int = int(SCREEN_WIDTH/GRID_CELL_SIZE)
ROOM_SIZE_Y: int = int(SCREEN_HEIGHT/GRID_CELL_SIZE) - UI_SIZE

DEBUG_DRAW: bool = False
